### ISSUE TITLE
Add v to the version generated in the build packages

### ISSUE THREAD

**Issue by dajohi** [decred/decrediton#984]
Currently, the tarball is built as decrediton-${version}.tar.gz.

Change it to decrediton-v${version}.tar.gz

**Comment by brunobraga95** [comment]
I think this was already done, should this issue be closed?

**Comment by dajohi** [comment]
Done by which commit?

**Comment by alexlyp** [comment]
Yah it's still being done by hand, definitely not fixed.  This requires some twiddling with electron-builder options/config or possibly submitting a PR to that repo
